### ISSUE TITLE
Order of grid classes

### ISSUE THREAD

**Issue by gintsmurans** [MWDelaney/bootstrap-4-shortcodes#11]
Hi!

Looks like if I am writing the shortcode this way: [column xs="12" md="6"] or this way: [column md="6" xs="12"], it would generate `<div class="col-md-6 col-xs-12">` for both shortcodes. Am I missing something or this is how the plugin works?

**Comment by MWDelaney** [comment]
Hi,
This plugin doesn't work yet. It should not be considered for use on a real site yet.

**Comment by gintsmurans** [comment]
Thats unfortunate..

**Comment by gintsmurans** [comment]
Btw, are you accepting pull requests?

**Comment by MWDelaney** [comment]
I am!
