### ISSUE TITLE
Fatal Error: Class 'MWD\BS4Shortcodes\Init' not found

### ISSUE THREAD

**Issue by Ricoder92** [MWDelaney/bootstrap-4-shortcodes#4]
Hello,

at first, thank you for this plugin! 

I installed your plugin on my localhost wordpress and it works fine for me.

But when i try to activate it on a wordpress which is installed on a webserver, there comes the following error:

Fatal error: Class 'MWD\BS4Shortcodes\Init' not found in /mnt/xxxx/xx/xx/xxxxxxx/htdocs/xxxx/wp-content/plugins/bootstrap-4-shortcodes-master/bootstrap-4-shortcodes.php on line 40

Wordpress Version: 4.75 on both systems. 

Any suggestions what can i do to fix this problem?

Thank you.

Best Regards,
Rico

**Comment by carlosruminott** [comment]
Hi,
I have the same problem.
Thanks!

**Comment by jj-walker** [comment]
I am also having this problem.  My local PC environment is running php 5.4.12 (wamp server) the server is running 5.4.45-0+deb7u2.

**Comment by jj-walker** [comment]
This is a case sensitivity issue.  Changing the class names to lowercase fixes the problem.

**Comment by MWDelaney** [comment]
At the time of this issue, this plugin wasn't production ready. It still isn't, but I'm working on it.
