### ISSUE TITLE
Help window always visible under post content box

### ISSUE THREAD

**Issue by davejm** [MWDelaney/bootstrap-4-shortcodes#5]
It seems something broke when I upgraded to Wordpress 4.8.1. The help button no longer does anything and the modal is always visible under the post content box.

**Comment by MWDelaney** [comment]
Hi. As noted in the readme, this plugin is definitely not ready for production use. I haven't had the time to work on it lately (though I still plan to finish it up), but I expect this and other (possibly more serious) bugs will persist until I can make a real go of finishing it. 

Sorry about that.
